[package]
name = "aoc-2024"
version = "0.1.0"
edition = "2024"

[lib]
doctest = false

[[bin]]
name = "aoc-2024"
path = "src/main.rs"
test = false

[dependencies]
clap = { version = "4.4.10", features = ["derive"] }
indexmap = "2.7.0"
rustc-hash = "2.0.0"
winnow = "0.6.20"
